// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRandomTemperatureChange();

float distance_cm;
float moving;
float randomTemperature;

void initProperties(){

  ArduinoCloud.addProperty(distance_cm, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moving, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(randomTemperature, READWRITE, ON_CHANGE, onRandomTemperatureChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
